parameters:
- name: stageName # Name of the stage.
- name: imageName # Name of the agent to work on.
- name: runTests
  type: string
  default: 'On'
  
stages:
- stage: ${{ parameters.stageName }}
  dependsOn: []
  jobs:
  - job: Build_and_Test
    displayName: Build and Test
    condition: ne(${{ parameters.runTests }}, 'Off')

    pool:
      vmImage: ${{ parameters.imageName }}
    
    # Configure this to run for both Debug and Release configurations
    strategy:
      matrix:
        debug:
          BuildConfiguration: Debug
        release:
          BuildConfiguration: Release 
    
    variables:
      - group: InternalKeys
      - name: RestoreBuildProjects
        value: '**/*.sln'
    
    steps:
    - checkout: self
      lfs: true
      submodules: recursive
        
    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet Packages'
      retryCountOnTaskFailure: 3
      inputs:
        command: 'restore'
        projects: '$(RestoreBuildProjects)'
        feedsToUse: 'select'
        vstsFeed: '$(InternalFeedId)'
    
    - task: DotNetCoreCLI@2
      displayName: 'Test'
      inputs:
        command: 'test'
        projects: '$(RestoreBuildProjects)'
        arguments: '-c $(BuildConfiguration) --no-restore'
        testRunTitle: '$(BuildConfiguration)'
      # Changed to use the 'no supported I/O' variant until the underlying issue is resolved: https://github.com/51Degrees/device-detection-dotnet/issues/18
      env:
        SUPER_RESOURCE_KEY: $(SuperResourceKey_NoSupportedIO)
      
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact' 
  